DEATHTYPE( dtNONE,			none )
DEATHTYPE( dtAXE,			axe )
DEATHTYPE( dtSG,			sg )
DEATHTYPE( dtSSG,			ssg )
DEATHTYPE( dtNG,			ng )
DEATHTYPE( dtSNG,			sng )
DEATHTYPE( dtGL,			gl )
DEATHTYPE( dtRL,			rl )
DEATHTYPE( dtLG_BEAM,		lg_beam )
DEATHTYPE( dtLG_DIS,		lg_dis ) // discharge
DEATHTYPE( dtLG_DIS_SELF,	lg_dis_self ) // sometimes this sort of discharge happens in dmm > 3
DEATHTYPE( dtHOOK,			hook )
DEATHTYPE( dtCHANGELEVEL,	changelevel )
DEATHTYPE( dtLAVA_DMG,		lava )
DEATHTYPE( dtSLIME_DMG,		slime )
DEATHTYPE( dtWATER_DMG,		water )
DEATHTYPE( dtFALL,			fall )
DEATHTYPE( dtSTOMP,			stomp )
DEATHTYPE( dtTELE1,			tele1 )
DEATHTYPE( dtTELE2,			tele2 )
DEATHTYPE( dtTELE3,			tele3 )
DEATHTYPE( dtEXPLO_BOX,		explo_box )
DEATHTYPE( dtLASER,			laser )
DEATHTYPE( dtFIREBALL,		fireball )
DEATHTYPE( dtSQUISH,		squish )
DEATHTYPE( dtTRIGGER_HURT,	trigger )
DEATHTYPE( dtSUICIDE,		suicide ) // client use /kill command
DEATHTYPE( dtUNKNOWN,		unknown )
